### ISSUE TITLE
0 to Many / 0 to 1

### ISSUE THREAD

**Issue by MSAskew** [holistics/dbml#1]
The ability to register a 0 to Many or 0 to 1 relationship seems to be lacking currently.

This is the only thing preventing me easily being able to use the tool at work and its much better than draw.io so I’d preferably like to be able to!

**Comment by nvquanghuy** [comment]
Thanks @MSAskew this is good feedback, we'll add to our roadmap. The concept of zero-to-many is new to me though. Could you share any specific example on this front?

**Comment by MSAskew** [comment]
It was mentioned as feedback to a work scheme we were setting up.

Concept being when mapping out some Jira data that an Epic may have many issues, but an issue may have no Epic, or one epic.

Googling since then seems to imply this is just an optional 1-M relationship though! What do you think?

Sent from my iPhone

On 3 Jun 2019, at 05:41, Huy Nguyen <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks @MSAskew<https://github.com/MSAskew> this is good feedback, we'll add to our roadmap. The concept of zero-to-many is new to me though. Could you share any specific example on this front?

**Comment by nvquanghuy** [comment]
I responded this in the Twitter thread, pasting it here again for reference:

An easier example would be: A mentor has many students. A student can have zero or one mentor.

Yes it can be just a 1-to-many with a nullable students.mentor_id column. But semantically it makes sense ot have a dedicated 0-to-many. We'll think about it!

**Comment by lalessandrorizzo** [comment]
Can I ask why was this issue closed? 

I would be very interested in being able to annotate a relationship with whether it is mandatory or optional. Any plans to add this functionality?

**Comment by karmakaze** [comment]
What good is a standardized markup language that can't represent a `1---o` relationship?

**Comment by TeaNguyen** [comment]
Optional refs have been fully supported in dbml version 9.0.0. You can check the doc here: https://dbml.dbdiagram.io/docs#relationships--foreign-key-definitions
