### ISSUE TITLE
primary key for multiple columns

### ISSUE THREAD

**Issue by benjamin-loesch** [holistics/dbml#10]
Is there a way to set a primary key for multiple columns?

For example, there is a one-to-many table with additional columns and all columns in total are the primary key?

```
table model_has_permissions {
  permission_id int(10) [unsigned]
  model_type varchar(255)
  model_id bigint(20) [unsigned]

  primary_keys {
    permission_id,
    model_id,
    model_type
  }
}
```

**Comment by nvquanghuy** [comment]
Thanks for the question! It's something that in our roadmap. Once done, the syntax would look like this:

```Table users {
	first_name varchar
	last_name varchar

	indexes {
		(first_name, last_name) [pk]
	}
}```

This is because a primary key is also an index.

**Comment by benjamin-loesch** [comment]
Nice! Can't wait to use it :)
