### ISSUE TITLE
Code not compiled in real time

### ISSUE THREAD

**Issue by ZhengxunWu** [holistics/dbml#105]
How to compile/interpret my code? Now it seems no matter how I changed my code, the visualizer doesn't change. I am pretty new to this software. thanks in advance.

**Comment by nvquanghuy** [comment]
Hi @ZhengxunWu are you talking about DBML or about dbdiagram? I checked dbdiagram and it looks normal to me. Can you please share screenshot and the code you type?

**Comment by ZhengxunWu** [comment]
Thank you for your quick reply. It's an error on my end. Fixed now.
