### ISSUE TITLE
Composite Key expects a valid name instead of brackets ()

### ISSUE THREAD

**Issue by Qoyyuum** [holistics/dbml#116]
Version: dbdocs/0.3.0 Win 10 64 bit node-v12.16.2

My DBML:

```
Table LOTS {
  DISTCODE char [not null, note: 'District Code']
  BOOKCODE char [not null]
  LOTNUM int [not null]
  
  Indexes {
    (DISTCODE, BOOKCODE, LOTNUM) [pk]
  }
}

Table CONDITIONS {
  DISTCODE char [not null]
  BOOKCODE char [not null]
  LOTNUM int [not null]
}

Ref: LOTS.(DISTCODE, BOOKCODE, LOTNUM) > CONDITIONS.(DISTCODE, BOOKCODE, LOTNUM)
```

Error message after running `dbdocs build my.dbml` :

`Failed: You have syntax error in LRS.dbml line 56 column 11. Expected valid name but "(" found`

But when tried over at dbdiagram.io, no warning or error.

**Comment by tuanmonn** [comment]
Hello Abdul, dbdocs maker here. 

I'm sorry this happened to you. It is due to a small error in the dbdocs system that has not caught up with the new changes of DBML. We're working on this issue and will release the fix very soon!

**Comment by tim-rabouille** [comment]
Hi @tuanmonn 
Same error here, any news? thanks

**Comment by KevinTanjung** [comment]
Hi @tuanmonn, any update on this matter?

**Comment by TeaNguyen** [comment]
We're working on bringing it to the database documentation & the diagram visualization. We'll try to get it done in the next several weeks.

**Comment by TeaNguyen** [comment]
Hey guys, we just supported the composite foreign keys for the dbdocs! Here is the [release note](https://dbdocs.io/docs/our-roadmap#-composite-foreign-keys---jul-14-2021)
