### ISSUE TITLE
TypeError: parser.parse is not a function

### ISSUE THREAD

**Issue by nguyenphucthinh** [holistics/dbml#122]
Hi,

i'm trying to user DBML Core with GULP.
My objectif is very simple
i use 
`gulp watch` 
to track changes of dbml files
for every update, i will check validation of dbml files (syntax and logic)

when i commit and push code to github or bitbucket, pipeline will execute
`dbdocs build database.dbml  --project=powodb`

i use this script for dbml validation
`
const { Parser } = require('@dbml/core');
`
`
const parser = new Parser();
`
`
const dbml = fs.readFileSync('./database.dbml', 'utf-8');
`
`
const schema = parser.parse(dbml, 'dbml');
`

but i got this error
`
TypeError: parser.parse is not a function
`
Holistic team can check it please ?
Many thanks

**Comment by phuongduyphan** [comment]
Hi @nguyenphucthinh ,

The docs for the package `@dbml/core` on `dbml.org` website is a bit outdated for now. We will update this asap. 

Sorry for the inconvenience. Will keep you updated when this issue is fixed.

**Comment by victormovchan** [comment]
Hi @phuongduyphan,
is there any progress on updating the docs?

**Comment by khanhtmn** [comment]
Hi @nguyenphucthinh , 

Many thanks for raising the issue. Let me try to address it: 

1/ Currently `dbdocs` is using `@dbml/core` version `2.0.1` (not the latest one `2.1.1`) so please make sure your `dbml` package is this version.  
2/ `Parser` in dbml is a static method, so you can call on the class itself:
```
const { Parser } = require('@dbml/core');
const dbml = fs.readFileSync('./database.dbml', 'utf-8');
const schema = Parser.parse(dbml, 'dbml');
```
3/ `dbdocs` already validate the dbml files before building so you don't need to do validation in step 2 too. 

Hope it helps resolve your issue. Please let me know if you have any other question.

**Comment by khanhtmn** [comment]
Hi @victormovchan ,

As mentioned above, currently `dbdocs` is using `@dbml/core` version `2.0.1` so probably you'd need to downgrade to that version (the latest one is `2.1.1`) for a quick fix. Sorry we haven't found time to update the docs yet. Hope you enjoy `dbdocs` and `dbml` :D

**Comment by victormovchan** [comment]
Great! thanks for the detailed answer!

**Comment by khanhtmn** [comment]
Awesome. I'm glad that helps guys! @nguyenphucthinh  @victormovchan
