### ISSUE TITLE
sql2dbml fails on Postgres array data type "character varying[]"

### ISSUE THREAD

**Issue by MikeGriffinReborn** [holistics/dbml#126]
See example below ...

**createWhitelistRoles" character varying[],**

that column causes sql2dmbl to choke ...

**Comment by nvquanghuy** [comment]
You should wrap it with double quote and it should work:

```
Table test {
  "createWhitelistRoles" "character varying[]"
}
```

**Comment by MikeGriffinReborn** [comment]
But this was the output of a calling CREATE SCRIPT from within PGAdmin, I
was converting SQL to DBML, should we really have to hand-edit out scripts?

**Comment by MikeGriffinReborn** [comment]
But this was the output of a calling CREATE SCRIPT from within PGAdmin, I was converting SQL to DBML, should we really have to hand-edit out scripts?

**Comment by nvquanghuy** [comment]
Ah I see what you mean. This looks like a parsing error of dbml then. Let us look into this.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/192
