### ISSUE TITLE
sql2dbml fails for PostGres ADD COLUMN

### ISSUE THREAD

**Issue by ayushais** [holistics/dbml#129]
I am generating the SQL file using alembic and I get the following error  when I use sql2dbml command

`Expected "CHECK", "CONSTRAINT", "EXCLUDE", "FOREIGN", "PRIMARY", or "UNIQUE" but "C" found.`
and this the SQL command
`ALTER TABLE <table name> ADD COLUMN valid BOOLEAN;`

Is this not supported for postgres yet?

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/256
