### ISSUE TITLE
Feature requests for dbdiagram.io/d editor

### ISSUE THREAD

**Issue by danielh-official** [holistics/dbml#130]
- Soft-wrap on editor so that user doesn't have to scroll horizontally
- Fix notes so that they show completely when hovering over the field/table and aren't clipped at the end

**Comment by nvquanghuy** [comment]
Thank you for the suggestions! I've noted down the suggestions!

For next time, any suggestions for dbdiagram, could you share it in the dbdiagram forum. This Github is reserved for DBML (the DSL language behind dbdiagram).

https://community.dbdiagram.io/
