### ISSUE TITLE
sql2dbml fails for Mysql auto_increment

### ISSUE THREAD

**Issue by haily-tripla** [holistics/dbml#135]
Hi, sql2dmbl returns an error when my table definition includes auto_increment

Sample create table script
```
CREATE TABLE test_table
(
   id          INT            NOT NULL AUTO_INCREMENT
   PRIMARY KEY (id)
)
;
```

Error:
You have a syntax error at "test_db.ddl" line 3 column 40. Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "DEFERRABLE", "GENERATED", "INITIALLY", "NOT", "NULL", "PRIMARY", "REFERENCES", or "UNIQUE" but "A" found.

Can you please support mysql auto increment?

**Comment by khanh-tran-quoc** [comment]
Add a comma at the end of each line and it should work
```sql
CREATE TABLE test_table
(
   id          INT            NOT NULL AUTO_INCREMENT  ,
   PRIMARY KEY (id)
)
;
```
