### ISSUE TITLE
how to setup an auto-incrementing primary key that starts at a specific number? 

### ISSUE THREAD

**Issue by hadv** [holistics/dbml#137]
in mysql,  for instance, we can set auto-incrementing that start from a value like below

```
ALTER TABLE table_name AUTO_INCREMENT=1001;
```

Can we do this in dbml? 

Thank you so much!

**Comment by nvquanghuy** [comment]
Hi @hadv , currently in DBML we have auto-increment setting. 
https://www.dbml.org/docs/#column-settings

``
Table buildings {
  id integer [increment]
}
```

However you're right that we don't have custom-value increment yet. We can consider that but IMO it's not a high priority at the moment. Since DBML is also open-source, you're also welcome to open a PR to contribute to it :) I'll be happy to work with you and review the design + implementation.

**Comment by hadv** [comment]
yes, I'm moving to use **snowflake id** then the increment from a specific number is not urgent anymore ;)

**Comment by nvquanghuy** [comment]
Cool, thanks for the update.
