### ISSUE TITLE
Cannot Found SchemaExpoter

### ISSUE THREAD

**Issue by protyliss** [holistics/dbml#140]
Cannot found the `SchemaExporter` as explained on Document
I review the source of `@dbml/core`, But There has not it too.

Instead found `ModelExporter`, But Seems to be not work.

```
// TypeError: Cannot read property '1' of undefined
// @dbml\core\lib\export\PostgresExporter.js:289:36

ModelExporter.export(Parse.parse([string], 'dbml'), [format]);
ModelExporter.export(Parse.parse([string], 'dbml').schemas[0].tables, [format]);
ModelExporter.export(Parse.parse([string], 'dbml').schemas[0].tables.schema, [format]);
```

Maybe wrong of the arguments.
How to get sql from schema object as each table?

**Comment by phuongduyphan** [comment]
Hi @protyliss,
The correct way to get sql from your dbml file should be like this: 
```
const { exporter } = require('@dbml/core');
const sql = exporter.export(source, 'mysql');
```
