### ISSUE TITLE
dbdiagram.io: Error with composite foreign keys when importing from MySQL

### ISSUE THREAD

**Issue by lHersey** [holistics/dbml#142]
When importing from mysql with a table having the next FK:

``CONSTRAINT `FK_Cities_States_StateId_CountryId` FOREIGN KEY (`StateId`, `CountryId`) REFERENCES `States` (`Id`, `CountryId`) ON DELETE CASCADE``

Throws the following error
`(1:1) Two endpoints have unequal number of fields`

But the both sides of the relationship have the same number of fields (The script works on MySQL)
The documentation says that composite FK are supported (https://www.dbml.org/docs/#relationships-foreign-key-definitions)

Full Example:
```
CREATE TABLE `Cities` (
  `Id` int NOT NULL,
  `CountryId` int NOT NULL,
  `StateId` int NOT NULL,
  `Name` varchar(32) NOT NULL,
  PRIMARY KEY (`Id`,`StateId`,`CountryId`),
  KEY `IX_Cities_CountryId` (`CountryId`),
  KEY `IX_Cities_StateId_CountryId` (`StateId`,`CountryId`),
  CONSTRAINT `FK_Cities_Countries_CountryId` FOREIGN KEY (`CountryId`) REFERENCES `Countries` (`Id`) ON DELETE CASCADE,
  CONSTRAINT `FK_Cities_States_StateId_CountryId` FOREIGN KEY (`StateId`, `CountryId`) REFERENCES `States` (`Id`, `CountryId`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `Countries` (
  `Id` int NOT NULL,
  `Name` varchar(32) NOT NULL,
  PRIMARY KEY (`Id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;

CREATE TABLE `States` (
  `Id` int NOT NULL,
  `CountryId` int NOT NULL,
  `Name` varchar(32) NOT NULL,
  PRIMARY KEY (`Id`,`CountryId`),
  KEY `IX_States_CountryId` (`CountryId`),
  CONSTRAINT `FK_States_Countries_CountryId` FOREIGN KEY (`CountryId`) REFERENCES `Countries` (`Id`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
```

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/192

**Comment by dweissjcs** [comment]
Hello, I've just encoutered the same problem.. Tried example above and it is not working too. Could you check please?

**Comment by cbase-dai-miyahara** [comment]
I have just encountered the same one...

**Comment by TeaNguyen** [comment]
We've tried it again & it still worked. Make sure you test it with the `dbml/cli` version `2.3.1` & include the `--mysql` option

**Comment by NQPhuc** [comment]
This issues is related to MySQL and have been resolved. For PostgresSQL composite FK importing errors, please refer to https://github.com/holistics/dbml/issues/248
