### ISSUE TITLE
Converting into dbml with utf-8 models

### ISSUE THREAD

**Issue by adamzelfel** [holistics/dbml#148]
I solved this problem by replacing 
- with open("output.dmbl", "w")
+ with open("output.dmbl", "w", encoding='utf-8')

i could be helpful for someone

Honestly,
excuse me if i am doing something wrong with writing here, this is my first-time "bugfix" of public library. Just thought it could be helpful for someone.

**Comment by NQPhuc** [comment]
This is a Python syntax. Issues related to the python parser for DBML should be posted there instead: https://github.com/Vanderhoof/PyDBML

Thanks
