### ISSUE TITLE
Postgres schema name in types

### ISSUE THREAD

**Issue by incompletude** [holistics/dbml#149]
```sql
CREATE TYPE "public"."payment_type_enum" AS ENUM ('refunded', 'expired', 'canceled', 'paid', 'in_analysis', 'pending');
```

When my type contains the schema name it breaks the cli.

**Comment by nikelborm** [comment]
Блин, спасибо чувак, что сказал причину этого бага. Я убрал "public". и у меня наконец получилось перевести эту схему в dbml, а потом её опубликовать.
