### ISSUE TITLE
dbml-renderer project

### ISSUE THREAD

**Issue by lucastorri** [holistics/dbml#154]
Hi Everyone, and thank you for creating DBML and related tools.

They have been so useful to us that we often use the format to create internal documentation. At times, we inline those in markdown documents, and we needed something that would render them as images as part of our CI.

That's why we create a tool called `dbml-renderer`: https://github.com/softwaretechnik-berlin/dbml-renderer

It is a command-line tool and library written in Typescript and uses [dot](https://en.wikipedia.org/wiki/DOT_(graph_description_language)) to generate the diagrams. It can also be used directly in the browser because it uses [viz.js](https://github.com/mdaines/viz.js) to generate the SVG images.

We were wondering what would be the general feedback about it and if it would make sense to add it to the "Community Contributions" section of this project and also in https://www.dbml.org/home/#community-contributions

I wasn't sure how and whether this should be done, so I decided to create this issue to check what to do.

Once again, thank you for all.

**Comment by nvquanghuy** [comment]
This is fantastic @lucastorri, please feel free to open a pull request to include it to our Community Contributions section (both website and Github readme.md)!

Sorry for the delay as we're a bit busy during this period, but we'll be getting more involved with dbml soon.

**Comment by aisbergde** [comment]
@lucastorri I see, you provide what I am looking for, an alternative way to visualize DBML scripts! I will test it!

**Comment by lucastorri** [comment]
Dear @nvquanghuy, I'm terribly sorry for the delay. As you suggested, I created a PR (https://github.com/holistics/dbml/pull/161) to add the links. I believe I got them in the right place. Could you please have a look and let me know?

Thank you once again!

**Comment by TeaNguyen** [comment]
Hi @lucastorri, we've merged your PR & deployed it on the Community Contributions sections ([website](https://www.dbml.org/home/#community-contributions) & [GitHub readme](https://github.com/holistics/dbml/#community-contributions)). Thank you for your contribution!
