### ISSUE TITLE
documentation - missing example how to create index with name

### ISSUE THREAD

**Issue by aisbergde** [holistics/dbml#157]
https://www.dbml.org/docs/#index-definition

wrong example, missing name in this example

>Index with single field (with index name): CREATE INDEX on users (created_at)

And there is no example how to define a named index

**Comment by TeaNguyen** [comment]
Hi @aisbergde,

We've just updated the docs for **create index with name** here: https://www.dbml.org/docs/#index-definition
Thank you.
