### ISSUE TITLE
Bug Cyrillic

### ISSUE THREAD

**Issue by 0x000777** [holistics/dbml#166]
If you use Cyrillic on your site, you can catch an error with your chosen font. Your "Droid Sans Mono" font does not support Cyrillic.

Take a look at the attachment.

![image](https://user-images.githubusercontent.com/17083227/114571848-a2244e00-9c7f-11eb-9bf3-bdda3d00f9da.png)

sample
`"publishing" tinyint(1) [not null, default: "0", note: 'В процессе публикации'`

**Comment by ismaxim** [comment]
I propose to use the [Fira Code](https://github.com/tonsky/FiraCode). It's free also supports many languages, including Cyrillic, and easily integrates by [Google Fonts](https://fonts.google.com/specimen/Fira+Code)

**Comment by nguyenalter** [comment]
This issue is fixed in the latest version of dbdiagram
![image](https://user-images.githubusercontent.com/44129390/225572537-bdf6d304-217d-4da1-8ba8-915374e007f8.png)
