### ISSUE TITLE
Grouping Tables

### ISSUE THREAD

**Issue by MarsSu0618** [holistics/dbml#169]
### Problems
Hi, everyone. I want to ask about dbml. Can we group tables? just categorize some tables with dbml syntax.
Hope someone can answer about this problem, thank you.

**Comment by TeaNguyen** [comment]
Yes, we do support TableGroup syntax - but it’s not propagated to dbdocs, only in dbdiagram.
You can check it on the [DBML docs - TableGroup](https://www.dbml.org/docs/#tablegroup)
