### ISSUE TITLE
markdown language is not supported in table's notes

### ISSUE THREAD

**Issue by perryexpress** [holistics/dbml#186]
markdown language is not supported except for project's notes.

**Comment by NQPhuc** [comment]
Hi, AFAIK, you can write note with markdown syntax anywhere using by putting it between ''' ''' (3 single quotes). For example:
```
table  user{
  id integer [primary key, increment]
  name varchar (20) [note: 'some note abc']
  job job_status [note: '''
    # Field's note

    **markdown content here**
  ''']
  Note: '''
    # Table's note 
	
    **markdown content here** 
  '''
}
```
If there's any case that we overlooked, please let me know.

**Comment by TeaNguyen** [comment]
Markdown support for the notes of tables & fields

![Screen Shot 2022-02-14 at 11 23 31](https://user-images.githubusercontent.com/12984025/153799859-e865d657-7109-4f27-9bef-9adcae02b5cd.png)
![Screen Shot 2022-02-14 at 11 24 37](https://user-images.githubusercontent.com/12984025/153799866-176e68f8-ee10-40be-9fbf-e0aa49c92e0c.png)
