### ISSUE TITLE
Autoincrement

### ISSUE THREAD

**Issue by jhondev** [holistics/dbml#2]
Is there any way to define autoincrement fields? I have used [auto increment] in dbdiagram.io but it doesn't work

**Comment by nvquanghuy** [comment]
Thanks @jhondev, this is something we're working on. Once ready it'll look like:

```Table users {
  id integer [pk, increment]
  name varchar [not null]
}```

https://www.holistics.io/community/t/auto-increment-field/75

**Comment by bf** [comment]
@jhondev for PostgreSQL you can just use the `serial` data type, e.g.

``Table users {
  id serial [pk]
  name text
}``
