### ISSUE TITLE
A new DBML parser package written on PHP for php developers

### ISSUE THREAD

**Issue by butschster** [holistics/dbml#201]
Hi guys! I developed a PHP package https://github.com/butschster/dbml-parser. I want to be in section "Community Contributions" on your site :)

Thank you!

**Comment by TeaNguyen** [comment]
Really appreciate your work. We'll add it in the "Community Contributions" section.

Thank you for your contribution!

**Comment by TeaNguyen** [comment]
Your work is now on the Community Contributions sections (website & GitHub readme). 
Thank you for your contribution!

**Comment by butschster** [comment]
Thank you!
