### ISSUE TITLE
Support for Delimited Identifier Syntax, among other issues (--mssql)

### ISSUE THREAD

**Issue by spencer741** [holistics/dbml#208]
Reference: https://docs.microsoft.com/en-us/sql/relational-databases/databases/database-identifiers?redirectedfrom=MSDN&view=sql-server-ver15#classes-of-identifiers

A lot of schema generation tools (namely features in SSMS and .SQLPROJ tooling) automatically wrap all table names and field names in square brackets. Doesn't _seem_ like this is supported in DBML.

Also, I am running into multiple syntax errors on completely valid SQL that I am generating as well if anyone can help.

Looks like it has issues with the IDENTITY keyword coming directly after the TYPE definition.

```
CREATE TABLE [CodeDef] (
    [CdKey]                     BIGINT             IDENTITY (1, 1) NOT NULL,
    [Category]                  NVARCHAR (50)      NOT NULL,
    [Description]               NVARCHAR (100)     NULL,
    [Code]                      NVARCHAR (50)      NOT NULL,
    [ParentCdKey]               BIGINT             NULL,
    [UserMasterKeyAddedBy]      BIGINT             NOT NULL,
    [UserMasterKeyLastEditedBy] BIGINT             NULL,
    [AddedDtTm]                 DATETIMEOFFSET (7) NOT NULL,
    [LastEditedDtTm]            DATETIMEOFFSET (7) NULL,
    [EffectiveFromDtTm]         DATETIMEOFFSET (7) NOT NULL,
    [EffectiveThruDtTm]         DATETIMEOFFSET (7) NULL,
    CONSTRAINT [PK__CodeDef__4922449ECDD244C3] PRIMARY KEY CLUSTERED ([CdKey] ASC),
    CONSTRAINT [fk__CodeDef__ParentCdKey__CodeDef__CdKey] FOREIGN KEY ([ParentCdKey]) REFERENCES [CodeDef] ([CdKey]),
    CONSTRAINT [fk__CodeDef__UserMasterKeyLastEditedBy__UserMaster_UserMasterKey] FOREIGN KEY ([UserMasterKeyLastEditedBy]) REFERENCES [UserMaster] ([UserMasterKey])
);
```

This is completely valid in dbdiagram.io in Import -> Sql Server dialog (provided the other tables are referenced).

Could someone shed some light on this issue? Thanks!

**Comment by spencer741** [comment]
@phanbaominh @stepanic  @lucastorri @9diov @ilyakharlamov Tagging for visibility.

**Comment by NQPhuc** [comment]
Hi, it turns out that our JS module already supports importing from MS SQL to DBML but the `--mssql` option argument is not added to CLI modules. We'll fix this soon and add the option in the next release.

**Comment by spencer741** [comment]
@NQPhuc Wow. You all are on top of it with this project. Awesome response/fix time. Thanks!

**Comment by NQPhuc** [comment]
Added in 2.4.0
