### ISSUE TITLE
Comments exported to MySQL using wrong quote type

### ISSUE THREAD

**Issue by djpeach** [holistics/dbml#212]
The table definition:
```
Table Account {
  ID "int unsigned" [pk, increment, not null]
  
  Username varchar(255) [not null]
  Password varchar [not null]
  
  Note: 'The necessary details to identify and authenticate users'
}
```

The exported comment syntax: 
```ALTER TABLE `Account` COMMENT = "The necessary details to identify and authenticate users";```

Notice the double quotes on the comment string. MySQL expects single quotes.

**Comment by djpeach** [comment]
I also noticed the wrong quote type is used for default enums: 
```
`Status` ENUM ('Processing', 'Shipped', 'Delivered', 'Cancelled') NOT NULL DEFAULT "Processing";
```

**Comment by nguyenalter** [comment]
Fixed in https://github.com/holistics/dbml/pull/477
