### ISSUE TITLE
[question] can i use mysql binary option?

### ISSUE THREAD

**Issue by ysp1011** [holistics/dbml#216]
i tried sql2dbml. but it showed error.

sql :
create table `a` (
  `id` varchar(22) binary
);

error msg:
SyntaxError: You have a syntax error at "test.sql" line 2 column 3. Expected ")" or fields but "`" found.

how do i use mysql binary option?

**Comment by TeaNguyen** [comment]
Unfortunately, we don’t support that option from MySQL.
However, we’ve noted it to consider implementing in the future.

**Comment by NQPhuc** [comment]
Supported in https://github.com/holistics/dbml/pull/486
