### ISSUE TITLE
[Postgres] Parsing Error when identifiers have '.'

### ISSUE THREAD

**Issue by fbartho** [holistics/dbml#219]
I'm using `pg_dump --schema-only` to extract a schema from our Postgres DB

Then I'm executing `sql2dbml schema.sql -o schema.dbml --postgres`

This barfs on the following sql statement:

```sql
--
-- Name: contact_type_enum; Type: TYPE; Schema: public; Owner: user
--

CREATE TYPE public.contact_type_enum AS ENUM (
    'family',
    'friend',
    'insurance_company',
    'medical_professional',
    'neighbor',
    'other'
);
```

It looks like `CREATE TYPE … ENUM` doesn't support `.` being in identifiers: https://github.com/holistics/dbml/blob/5c9a4adb45c508b7db132f09c699a2e33f5d1ab2/packages/dbml-core/src/parse/postgresql/Commands/Create_type/Create_type_enum.pegjs#L2

The equivalent for `table_name` is: https://github.com/holistics/dbml/blob/5c9a4adb45c508b7db132f09c699a2e33f5d1ab2/packages/dbml-core/src/parse/postgresql/Base_rules.pegjs#L4-L5
Which, as you can see, drops the namespace (in this case `public`)

**Comment by fbartho** [comment]
Workaround: strip `public.` from my input sql file before processing it

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/240
