### ISSUE TITLE
[Postgres] ALTER TYPE command not supported (should be ignored)

### ISSUE THREAD

**Issue by fbartho** [holistics/dbml#220]
I'm using `pg_dump --schema-only` to extract a schema from our Postgres DB

Then I'm executing `sql2dbml schema.sql -o schema.dbml --postgres`

This barfs on the following sql statement:
```sql
ALTER TYPE contact_type_enum OWNER TO "user";
```

I'm not sure, but I think there's a simple way to ignore commands such as `ALTER TYPE` by patching something in here: https://github.com/holistics/dbml/blob/5c9a4adb45c508b7db132f09c699a2e33f5d1ab2/packages/dbml-core/src/parse/postgresql/Commands/Ignore_syntax.pegjs#L1-L17

I'm not sure what the syntax would be though.

**Comment by depombo** [comment]
I just bumped into this. Running `pg_dump` with the `--no-owner` flag will fix it

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/256
