### ISSUE TITLE
[Postgres] ALTER TABLE … OWNER TO unsupported, should be ignored

### ISSUE THREAD

**Issue by fbartho** [holistics/dbml#221]
I'm using `pg_dump --schema-only` to extract a schema from our Postgres DB

Then I'm executing `sql2dbml schema.sql -o schema.dbml --postgres`

This barfs on the following sql statement:
```sql
ALTER TABLE organization_units OWNER TO "user";
```

I believe this should be ignored, but the ALTER TABLE command: https://github.com/holistics/dbml/blob/master/packages/dbml-core/src/parse/postgresql/Commands/Alter_table/Alter_table.pegjs is a little complex for me.

I think the fix could be by changing that grammar, or by adding something in the ignore file: https://github.com/holistics/dbml/blob/master/packages/dbml-core/src/parse/postgresql/Commands/Ignore_syntax.pegjs#L1-L17

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/256
