### ISSUE TITLE
[Postgres] Import fails on self referencing composite key

### ISSUE THREAD

**Issue by trietsch** [holistics/dbml#222]
Example of a failing import:
```
CREATE TABLE test_table (
	"name" varchar NOT NULL,
	id varchar NULL,
	linked_name varchar NOT NULL,
	CONSTRAINT test_table_pk PRIMARY KEY ("name", id),
	CONSTRAINT test_table_fk FOREIGN KEY (linked_name,id) REFERENCES test_table("name",id)
);
```

Results in: `(1:1) Two endpoints have unequal number of fields`

Any idea how to fix this? Or is this a bug?

**Comment by TeaNguyen** [comment]
We've found that it is a bug. The self-referencing composite key on Postgres is not working at the current. We'll fix it soon.

Maybe you can use the MySQL option as a workaround. We tested with the below example:

```
CREATE TABLE test_table (
   name varchar NOT NULL,
   id varchar NULL,
   linked_name varchar NOT NULL,
   PRIMARY KEY (name, id),
   CONSTRAINT test_table_fk FOREIGN KEY (linked_name,id) REFERENCES test_table(name,id)
);
```

Thank you for your report.

**Comment by trietsch** [comment]
Thanks, also for presenting a workaround!

**Comment by yarcowong** [comment]
Hello, sir, I'm not quite sure, 
```
Table tags {
    id bigint [not null, pk, increment]
    pid bigint [ref: < tags.id]
}
```
will output (`dbml2sql.cmd .\database.dbml --mysql`):
```sql
CREATE TABLE `tags` (
  `id` bigint PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `pid` bigint
);

ALTER TABLE `tags` ADD FOREIGN KEY (`id`) REFERENCES `tags` (`pid`);
```

It seems not right, I think it should be *ALTER TABLE `tags` ADD FOREIGN KEY (`pid`) REFERENCES `tags` (`id`);*

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/416
