### ISSUE TITLE
 Expected ",", "]", comment, or whitespace but "D" found.

### ISSUE THREAD

**Issue by arnsrk** [holistics/dbml#246]

**Comment by arnsrk** [comment]
I was getting the above error while Direction column name is used. What does it mean? Is it a reserve word. Please suggest a solution to it.

**Comment by arnsrk** [comment]
I was getting the above error while Direction column name is used. What does it mean? Is it a reserve word. Please suggest a solution to it.

**Comment by arnsrk** [comment]
Direction nvarchar (1) [default: 'D'] ,[ pk, unique,NOT NULL] //increaseing or decreasing \\

**Comment by NQPhuc** [comment]
Hi, could you provides the a sample of the input files that produces this error, as well as the cli command that you have executed. It would help us investigate your case further.

**Comment by nguyenalter** [comment]
Hi @arnsrk, your column definition is wrong because default value and other constraints are defined in 1 `[]` block, see: https://www.dbml.org/docs/#column-settings for column settings syntax. The valid column definition should be:
`Direction nvarchar(1) [default: 'D', pk, unique,NOT NULL]`
