### ISSUE TITLE
mysqldump --no-data mydb.sql > mydb.sql | sql2dbml --mysql  mydb.sql -o  mydb.dbml | Expected ")" or fields but "`" found.

### ISSUE THREAD

**Issue by arnoldasbet** [holistics/dbml#25]
Hi,
I wanted to check out dbml tool, but on my sample schema it throwns an error

I have dumped my database schema only like this:
`mysqldump --no-data mydb.sql > mydb.sql`

`sql2dbml --mysql  mydb.sql -o  mydb.dbml`
_**Expected ")" or fields but "`" found.**_

How do I fix this?

**Comment by khoahuynhf** [comment]
Hi @arnoldasbet, i'm Khoa from dbml team. Can you show me the dump file `mydb.sql` so that i can inspect the issue you are having?

**Comment by arnoldasbet** [comment]
Here is the pastebin link: https://pastebin.com/raw/eVTSC9xA

**Comment by khoahuynhf** [comment]
I have inspected the issue, currently we are not supporting ` ON UPDATE CURRENT_TIMESTAMP`.
So you can work-around by removing it.
We will have support for it in the next patch.
Thank you for your feedback.

**Comment by arnoldasbet** [comment]
I have removed them
`:%s/ ON UPDATE CURRENT_TIMESTAMP//g`

Now I get this:
**_ERROR: Expected ")" or fields but "C" found._**

I have removed these as well
`ON DELETE NO ACTION ON UPDATE NO ACTION`

**Comment by phuongduyphan** [comment]
Hi @arnoldasbet ,

We have just released a patch v1.1.1 to print the `Syntax Error` location on console. 

From now on, you can see the exact error location in your script. There are some SQL syntax that we haven't supported yet and it will report as `Syntax Error` as well. You can work-around this by removing the unsupported syntax.

Cheers !

**Comment by arnoldasbet** [comment]
Good patch! Cheers!

ERROR: You have a syntax error at "mydb.sql" line **_774 column 3_**. Expected ")" or fields but "l" found.
