### ISSUE TITLE
How to make a n,n relation between two table ?

### ISSUE THREAD

**Issue by yvesnormand** [holistics/dbml#255]
I know you can bound two table with [ref: < or > or - nameAttribute] but it create a 1,n 1,1 or N,1 relation. Isn't it possible to create a n,n relation ?

**Comment by lukew3** [comment]
> I know you can bound two table with [ref: < or > or - nameAttribute] but it create a 1,n 1,1 or N,1 relation. Isn't it possible to create a n,n relation ?

Relational databases don't have n,n or many-to-many relations. You have to create a junction table. See https://gist.github.com/anonymous/79c2eed2a634777b16ff for an example.
