### ISSUE TITLE
Postgres sql2dbml errors

### ISSUE THREAD

**Issue by yiziz** [holistics/dbml#277]
Hey,

Been running into a bunch of syntax issues like

```
ERROR: You have a syntax error at "schema copy.sql" line 41 column 12. Expected "COLUMN" or "TABLE" but "S" found.
```

from a Postgres schema dump I did on this sample project database - https://github.com/lorint/AdventureWorks-for-Postgres.

I put the schema dump into this gist: https://gist.github.com/yiziz/74b1cf6c3c0b4f8362c39d03c32c6a27

**Comment by buraksarica** [comment]
We've encountered a few similar errors using the sql2dbml too. The problem seems about the unsupported sql clauses. These clauses may not be about DB model so, should sql2dbml just ignore these? I just remove those lines and it worked at the end.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/416
