### ISSUE TITLE
Postgres types with multiple words doesn't work (like: "double precision")

### ISSUE THREAD

**Issue by eminfedar** [holistics/dbml#280]
DBML says column types must be one word. But Postgres has multiple word data types like `double precision`

For example this gives an error:
```sql
Table User {
  Field double precision
}
```
This should export a Postgres .sql file like this:
```sql
CREATE TABLE "User" (
  "Field" double precision
);
```

**Comment by databugs** [comment]
I am also experiencing the sma issue as @eminfedar

**Comment by eminfedar** [comment]
I have solved this by using `float8` data type, which is one word and same as `double precision`.

**Comment by databugs** [comment]
Thank you, this worked fine.

**Comment by nevmerzhitsky** [comment]
This issue blocks me from use of `dbml/cli`

**Comment by CramericaIndustries** [comment]
Every pg multiword data-type has a single word alias.
Like 'timestamptz' for 'timestamp with time zone'.

Full list: [https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE](https://www.postgresql.org/docs/current/datatype.html#DATATYPE-TABLE)
