### ISSUE TITLE
sql2dbml postgres is not able to able to understand casting

### ISSUE THREAD

**Issue by suchitgupta01** [holistics/dbml#281]
The sql2dbml is not able to understand the casting and fails with error "ERROR: You have a syntax error at "schema.sql" line 3 column. Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "GENERATED", "NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", or space but ":" found."
`
CREATE TABLE public.tests (
    id bigint NOT NULL,
    type character varying DEFAULT 'testing'::character varying
);
`

**Comment by pedrorenan** [comment]
I have the same problem here. I used a regex function to fix this.

**Comment by trckster** [comment]
It looks like `::` triggers error. I have the same problem for these lines:

`DEFAULT '6 mons'::interval`
`DEFAULT 'active'::"BuildingStatus"`
`DEFAULT 'progress'::character varying`
`+ one long constraint with ::`

**Comment by nevmerzhitsky** [comment]
This issue blocks me from using `dbml/cli`.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/issues/281
