### ISSUE TITLE
Facing challenges when compiling ERML into DBML

### ISSUE THREAD

**Issue by obadakhalili** [holistics/dbml#284]
I'm trying to compile [ERML](https://erml.netlify.app) into DBML by converting the AST generated by ERML parser into `Database` model, then export this into DBML using the exporter. And I'm facing these two challenges:
*  I don't know the data structure for `Database` model because it is not documented on your site and it is not typed-annotated in the project.
* I don't have access to the APIs of `Database` model because it is not exported by @dbml/core.

Can you suggest workarounds for the mentioned problems? Or do you suggest a different means to compile ERML into DBML?

**Comment by baolequoc** [comment]
You can check data structure in `packages/dbml-core/types/model_structure/`
And you can try `import { importer } from '@dbml/core';` to import and  `import { ModelExporter } from '@dbml/core';` to export

**Comment by obadakhalili** [comment]
Thanks for the answer man.
