### ISSUE TITLE
Importing removes all tables that exist in a diagram

### ISSUE THREAD

**Issue by AlmostRemember** [holistics/dbml#288]
I am testing the 'Import from SQL Server' function. When I import a table everything that already exists in the diagram is removed. I would like the option to preserve any existing tables when importing. This would allow importing tables one at a time, when they become relevant to a diagram.

**Comment by TeaNguyen** [comment]
Closed. Moved to the relevant [thread](https://community.dbdiagram.io/t/feature-request-update-diagram-from-sql-server-import/812/3) on dbdiagram Community.
