### ISSUE TITLE
Composite PK from SQL loses order when translated to dbml

### ISSUE THREAD

**Issue by state303** [holistics/dbml#299]
Holla, I am very much enjoying the dbml and so on, but I have one, serious issue while using this.

```sql
CREATE TABLE IF NOT EXISTS artist_url (
  url_hash INTEGER NOT NULL,
  url VARCHAR(2048) NOT NULL,
  artist_id INTEGER NOT NULL CONSTRAINT fk_artist_url_artist_id_artist REFERENCES artist,
  PRIMARY KEY (artist_id, url_hash)
);
```
Currently translates to...

```dbml
Table artist_url {
    "url_hash" INTEGER [not null]
    "url" varchar (2048) [not null]
    "artist_id" INTEGER [not null]
    indexes {
        (url_hash, artist_id) [pk]
    }
}
```

Ordering of index is too important, but it seems there is no way to fix this.
I would like to know if I could PR to resolve this issue.
OR, I would like to know if there is any option to keep index order safe.

**Comment by NQPhuc** [comment]
Hi state303, 

Due to an oversight, the fields order of composite primary keys is currently also the order in which the fields are defined in the table.

For your case, as a workaround, you can try changing the column order so that `artist_id` is defined before `url_hash`. Like this:
```
CREATE TABLE IF NOT EXISTS artist_url (
  artist_id INTEGER NOT NULL CONSTRAINT fk_artist_url_artist_id_artist REFERENCES artist,
  url_hash INTEGER NOT NULL,
  url VARCHAR(2048) NOT NULL,
  PRIMARY KEY (artist_id, url_hash)
);
```

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/416
