### ISSUE TITLE
Composite Keys for Many-to-Many relationships

### ISSUE THREAD

**Issue by Maxiride** [holistics/dbml#3]
Many to many relationships handled with composite keys aren't that uncommon, is it a feature planned to be implemented?

**Comment by nvquanghuy** [comment]
Thanks! We do plan to support composite foreign keys (or even primary keys). When it does, it'll probably look like:

```
Table users as U {
  id1 integer
  id2 integer
}

Table posts as P {
  user_id1 integer
  user_id2 integer
}

Ref a {
  (P.user_id1, P.user_id2) > (U.id1, U.id2)
}

```

As for many-to-many with composite keys, I don't quite understand what you mean. Could you share an example?

**Comment by Maxiride** [comment]
> As for many-to-many with composite keys, I don't quite understand what you mean. Could you share an example?

I've actually expressed myself badly. The real question was about composite keys which I've often used to build a table holding the many to many relationships like:

```
--pseudo code
Table posts as P {
  post_id integer primary key
}

Table tags as T {
  tag_id integer primary key
}

Table posts_tags {
  tag_id references tag_id1
  post_id references post_id1

  composite key (tag_id, post_id)
}
```

So that in the table `posts_tags` I have a composite key uniquely identifying each row while also establishing the many-to-many relationship for all the tags within a post or all the posts with a specific tag.

Hope I clarified myself a bit ^^

**Comment by Maxiride** [comment]
I'm closing the issue ass it isn't a real _issue_ and you confirmed that this feature its on the roadmap.

**Comment by malshoffner** [comment]
Yet, this hasn't been added almost exactly 3 years since you closed it.

**Comment by TeaNguyen** [comment]
We did support composite foreign keys & many-to-many relationships. You can check out the [docs](https://www.dbml.org/docs/#relationships-foreign-key-definitions) for further information

**Comment by Jhonatan1599** [comment]
> We did support composite foreign keys & many-to-many relationships. You can check out the [docs](https://www.dbml.org/docs/#relationships-foreign-key-definitions) for further information

Could you add an example?

**Comment by thar24** [comment]
I can't see any mention or examples of composite keys in the docs. Is this currently implemented or still planned to be implemented?

**Comment by TeaNguyen** [comment]
You can find the mention and example of composite PK in the ["Index Definition" ](https://dbml.dbdiagram.io/docs#index-definition) section. For composite FK, you can find the mention at the end of the ["Relationships & Foreign Key Definitions"](https://dbml.dbdiagram.io/docs#relationships--foreign-key-definitions) section.
