### ISSUE TITLE
Clarification needed.

### ISSUE THREAD

**Issue by DeveloperRepoNSBM** [holistics/dbml#30]

**Comment by DeveloperRepoNSBM** [comment]
> Index Definition
Indexes allow users to quickly locate and access the data. Users can define single or multi-column indexes.

Table bookings {
  id integer [primary key]
  country varchar
  booking_date date
  created_at timestamp

  indexes {
      created_at [note: 'Date']
      booking_date
      (country, booking_date) [unique]
      booking_date [type: hash]
      (`id*2`)
      (`id*3`,`getdate()`)
      (`id*3`,id)
  }
}


in this context  (country, booking_date) [unique]
means country , booking date are unique individually or as a group

**Comment by nvquanghuy** [comment]
Hi there, it means there is 1 composite index on (country, booking_date), and the index is marked as unique. So yes it is as a group.

**Comment by DeveloperRepoNSBM** [comment]
> Hi there, it means there is 1 composite index on (country, booking_date), and the index is marked as unique. So yes it is as a group.

Thank you for the quick responce
