### ISSUE TITLE
[ Feature Request ] Add the ability to drag-and-drop the relationship lines to reposition around objects

### ISSUE THREAD

**Issue by johndahl-now** [holistics/dbml#305]
This tool is great and saves a lot of time! I still find myself spending a lot of time moving table objects around trying to make the relationship lines distinct, to avoid the overlapping that occurs when you have a lot of little tables in close proximity. It would be great if I could add elbows to the lines and reposition them around the other objects on the page.

**Comment by TeaNguyen** [comment]
Thank you for your suggestion.

This is a [feature suggestion](https://community.dbdiagram.io/t/manually-move-reference-lines/465) relevant to your inquiry. Perhaps you could vote for it.

I'm going to close this because this isn't a DBML issue.
