### ISSUE TITLE
Docs: Add a list of all the column types for dbml

### ISSUE THREAD

**Issue by chrissshan** [holistics/dbml#306]
I couldn't find a section that simply lists the syntax for the various column types on dbml

Expected:

Column types
- varchar
- integer
- ...

Coming from Prisma and it's more work than ideal to map things

**Comment by TeaNguyen** [comment]
The column types in DBML are dynamic. We don't actually restrict them to a specific list. Hence, people can freely define these column types as suitable for their familiar SQL.
