### ISSUE TITLE
Another request for dbdiagram

### ISSUE THREAD

**Issue by rboehm00** [holistics/dbml#323]
Being able to move the lines to get them away from each other and from going thru tables would be great - see picture below where you cannot see which line is which...

![MicrosoftTeams-image](https://user-images.githubusercontent.com/17429568/212176112-80c9072d-41d2-4666-a92e-e99f20f4a600.png)

**Comment by TeaNguyen** [comment]
Thank you for your suggestion.

This is a [feature suggestion](https://community.dbdiagram.io/t/manually-move-reference-lines/465) relevant to your inquiry. Perhaps you could vote for it.

I'm going to close this because this isn't a DBML issue.
