### ISSUE TITLE
Support referencing another DBML file

### ISSUE THREAD

**Issue by MrGossett** [holistics/dbml#34]
Working with large schemas can result in a single large DBML file. It would help reasoning about and maintaining a large schema if a single schema definition can span multiple files. That way, logically-grouped definitions can live in one file, and another file can reference those definitions by “including” them with a reference.

Something like this:
```dbml
include ‘enums.dbml’
```

**Comment by nvquanghuy** [comment]
This is a good idea and will certainly consider implementing.

What we have that's similar - but not quite what you asked for - is TableGroup: https://www.dbml.org/docs/#tablegroup-coming-soon

**Comment by HFSDev** [comment]
> This is a good idea and will certainly consider implementing.
> 
> What we have that's similar - but not quite what you asked for - is TableGroup: https://www.dbml.org/docs/#tablegroup-coming-soon

Is this going to be translated as schemas? If not, are you considering supporting schemas?

**Comment by nvquanghuy** [comment]
This won’t be translated as schemas. Think of it as a group of tables
related to one logic (eg bookings, transactions, auth, etc).

And yes we will support schemas.

**Comment by TheKnarf** [comment]
Perhaps there could be a `dbml-loader` for webpack and that loader could extend dbml to allow for includes.
