### ISSUE TITLE
support of jsonb in postgresql

### ISSUE THREAD

**Issue by nosovk** [holistics/dbml#340]
When I try to convert PGSQL ddl using `sql2dbml` I got errors on JSONB fields, for example:
```sql
create table profile.events
(
  id         uuid                     default gen_random_uuid() not null,
  data       jsonb                    default '{}'::jsonb       not null,
  created_at timestamp with time zone default now()             not null,
);
```
the part about `::jsonb` broke conversion

**Comment by nguyenalter** [comment]
We don't currently support the PostgreSQL type cast `::` operator. We'll let you know when we support this syntax.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/416
