### ISSUE TITLE
Implementing Generalization & specialization

### ISSUE THREAD

**Issue by Jannik-dev** [holistics/dbml#341]
Hi, I am quite new to dbml and I was searching for generalization & specialization in the documentation and couldn't find it. 

Can you specify it and if so how?

**Comment by nguyenalter** [comment]
We don't have a corresponding syntax for generalization & specialization concepts. However, you can write the DBML based on these concepts. For example: 
  ```
    Table person {
      id int [pk]
      role varchar
      name varchar
      email varchar
    }
    
    Table student {
      studentID int [pk]
      intake varchar
      major varchar
      personID int [ref: - person.id]
    }
    
    Table lecturer {
      lecturerID int [pk]
      skill varchar
      qualification varchar
      personID int [ref: - person.id]
    }
  ```
Result:
![image](https://user-images.githubusercontent.com/44129390/226510880-a710c136-d4db-40a8-8407-17be67f9012a.png)

**Comment by Jannik-dev** [comment]
Thanks for the quick response. I will use that approach
