### ISSUE TITLE
sql2dbml can not parse materialized views

### ISSUE THREAD

**Issue by suensummit** [holistics/dbml#345]
```
$ sql2dbml dump.sql --postgres
  ERROR: You have a syntax error at "dump.sql" line 1245 column 8. Expected "GLOBAL", "INDEX", "LOCAL", "SCHEMA", "SEQUENCE", "TABLE", "TEMP", "TEMPORARY", "TYPE", "UNIQUE", "UNLOGGED", or "VIEW" but "M" found.

  A complete log can be found in:
     /Users/suen.summit/Work/database/dump/dbml-error.log
```

The corresponding line 1245 starts with `CREATE MATERIALIZED VIEW`

It seems the support for parsing materialized view keyword is needed.

**Comment by huyphung1602** [comment]
Hi Summit Suen,

We do not yet support the `MATERIALIZED VIEW` syntax when parsing PostgreSQL to DBML.

In the future, we plan to improve the parsing behavior. We will notify you once it has been completed.

To avoid this problem, you might comment out or remove the Materialized View code before processing it to DBML.

**Comment by huyphung1602** [comment]
Yes, we have a guide for anyone who wants to contribute to DBML, which can be found here: https://github.com/holistics/dbml/blob/master/CONTRIBUTING.md

The current supported syntaxes are listed below: https://www.dbml.org/docs/
