### ISSUE TITLE
Website is down

### ISSUE THREAD

**Issue by gbanfalvi** [holistics/dbml#353]
Hiya, don't know if this is the best way to reach you but your docs website seems to be down.

**Comment by TeaNguyen** [comment]
Thank you for informing us about the problem!
We're looking into it.

**Comment by fredmanre** [comment]
I don't know if this is the correct channel to report this, but the webpage is still down! I've checked using several IPs to make sure isn't a country firewall issue and it is still there.

**Comment by TeaNguyen** [comment]
Hi guys,
We're having some problems with our domain and working on getting it back up.
In the meantime, here is another URL to read the DBML documentation: https://github.com/holistics/dbml/tree/master/dbml-homepage/docs

**Comment by TeaNguyen** [comment]
The DBML homepage has been relocated to a new domain: https://dbml.dbdiagram.io.
