### ISSUE TITLE
Docs: Composite PK documentation missing

### ISSUE THREAD

**Issue by tiazzz** [holistics/dbml#37]
Columns settings describe PK for a single column but refer the reader to Indexes for composite PKs; the Indexes section does not mention composite PKs.

**Comment by phuongduyphan** [comment]
Hi @tiazzz ,

Actually the composite PK docs is not missing but because it hasn't been supported yet. In the next several weeks, we will support composite PK / FK

**Comment by phuongduyphan** [comment]
Hi @tiazzz,

We've just updated the docs for composite PK here: https://www.dbml.org/docs/#index-definition
