### ISSUE TITLE
add to monaco

### ISSUE THREAD

**Issue by StathisKap** [holistics/dbml#405]
on https://dbdiagram.io/d, there is an editor with dbml syntax highlighting. The editor used is monaco, so if there was a directory on this project, will all the files needed (that include all the keywords and regex and all), along side a README of how to install it, was available, that'd be very useful

**Comment by huyphung1602** [comment]
Hi @StathisKap,

I am Huy from the dbdiagram team.

Could you please provide me with more information regarding the problem you're having? Or what are you attempting to accomplish?

**Comment by StathisKap** [comment]
Hello @huyphung1602 

I'm trying to recreate https://dbdiagram.io/d to build a react portfolio.
On the left side they have the monaco editor (which the same editor used for VSCode), with syntax highlighting for dbml.

The monaco editor doesn't do syntax hightlight for dbml natively, so that means that the language was added manually. I was wondering whether you guys could provide the files with all the regex and the keywords so that I can apply dbml syntax highlighting as well

**Comment by NQPhuc** [comment]
Hi @StathisKap,

We can't provide you the syntax highlight used for dbdiagram. 

As a starting point, you can check out the syntax highlight [definition](https://github.com/mattmeyers/vscode-dbml/blob/master/syntaxes/dbml.tmLanguage.json) in `vscode-dbml`, a dbml highlighter extension for vscode.
