### ISSUE TITLE
Is there a UI that comes with the repo?

### ISSUE THREAD

**Issue by nbenezri** [holistics/dbml#407]
For security reasons, I can't use [dbdiagram](https://dbdiagram.io/home).
I was curious if I can clone the repo in my environment and have a UI for it, just like the site?

**Comment by TeaNguyen** [comment]
It appears to be a very sad situation for us. But yeah, you can.
Our community also has an [open-source diagram visualizer](https://github.com/softwaretechnik-berlin/dbml-renderer). Perhaps you should take a look at it.

Thanks.
