### ISSUE TITLE
dbdiagram.io: Indexes don't support comments.

### ISSUE THREAD

**Issue by stepuncius** [holistics/dbml#42]
![Screenshot from 2019-11-12 15-03-40](https://user-images.githubusercontent.com/19806548/68670335-c1382100-055d-11ea-8142-82851c11f613.png)
![Screenshot from 2019-11-12 15-03-45](https://user-images.githubusercontent.com/19806548/68670336-c1d0b780-055d-11ea-810e-816a0c9137b7.png)
![Screenshot from 2019-11-12 15-04-01](https://user-images.githubusercontent.com/19806548/68670337-c1d0b780-055d-11ea-99d5-b07e5ef382be.png)
Non empty comments are also resticted:
![Screenshot from 2019-11-12 15-05-49](https://user-images.githubusercontent.com/19806548/68670417-f2185600-055d-11ea-8f09-4b506ef6996c.png)

**Comment by phuongduyphan** [comment]
Hi @stepuncius ,

Thanks for your report on this issue ! We will fix this asap ! Will keep you informed when it's fixed
