### ISSUE TITLE
error with default value when using dump schema db from postgres

### ISSUE THREAD

**Issue by labasubagia** [holistics/dbml#427]
Hi, I currently work using a dump database from Postgres

```bash
$ docker compose exec -T db pg_dump -s -U postgres my_db > doc/db/schema.sql
```

And here is the part of dump result
```sql
CREATE TABLE public.users (
    username character varying NOT NULL,
    hashed_password character varying NOT NULL,
    full_name character varying NOT NULL,
    email character varying NOT NULL,
    password_changed_at timestamp with time zone DEFAULT '0001-01-01 00:00:00+00'::timestamp with time zone NOT NULL, -- this is line 183
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
```

When I run 

```bash
$ sql2dbml --postgres doc/db/schema.sql -o doc/db/schema.dbml
```

There is an error like this:
```
ERROR: You have a syntax error at "schema.sql" line 183 column 82. Expected ")", ",", "CHECK", "CONSTRAINT", "DEFAULT", "GENERATED", "NOT", "NULL", "PRIMARY", "REFERENCES", "UNIQUE", or space but ":" found.
```

It turns out that the CLI cannot read the default value of `password_changed_at`

and the part that causes it is `'0001-01-01 00:00:00+00'::timestamp`

when I remove the default value, it works fine

---
database version 15.3
dump version 15.3

**Comment by NQPhuc** [comment]
Hi @labasubagia

**Comment by NQPhuc** [comment]
Hi @labasubagia,

You are correct that the current CLI cannot understand the default value of `password_changed_at` column.

For now, you can try removing the `::timestamp with time zone` part to get it working. For example:
```
CREATE TABLE public.users (
    username character varying NOT NULL,
    hashed_password character varying NOT NULL,
    full_name character varying NOT NULL,
    email character varying NOT NULL,
    password_changed_at timestamp with time zone DEFAULT '0001-01-01 00:00:00+00' NOT NULL,
    created_at timestamp with time zone DEFAULT now() NOT NULL
);
```

We're working on improving the postgres->dbml exporter and hopefully will resolves this issue in the future.

**Comment by labasubagia** [comment]
Looking forward to it @NQPhuc
