### ISSUE TITLE
boolean type for MSSQL

### ISSUE THREAD

**Issue by znog77** [holistics/dbml#44]
We ran into an odd issue. The following code will fail to export to MSSQL only:

Table true_or_false {
  tof boolean [default: 0] 
}

It will NOT fail if:
* Exported to MySQL o Postgres.
* tof is declared as "bool" instead of "boolean".
* default value is "false" instead of 0.

So we basically managed to hit the only case it fails!

**Comment by phuongduyphan** [comment]
Hi @znog77 ,

Thanks for reporting the issue. I confirm this is a bug in the exporting module. This will be fixed asap !

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/47
