### ISSUE TITLE
Show direction of relationship with arrows (UML style)

### ISSUE THREAD

**Issue by nfaugout-lucca** [holistics/dbml#45]
Hi,

The tool is great, and I am looking forward for the TableGroup feature.

I would like to know if it's possible to show the direction of the relationships with arrows. IMO it would show more clearly those relationship without the need to toggle the Highlight feature.

Here is an example to explain what I mean.

![chrome_U0sGS1VfSI](https://user-images.githubusercontent.com/2686141/70626381-9dcbc900-1c24-11ea-9733-c7c7f8b8f462.png)

=>

![arrows](https://user-images.githubusercontent.com/2686141/70626555-f8652500-1c24-11ea-9b95-c14553245556.png)

The standard around UML could be used, as explained here : https://www.talend.com/resources/data-model-design-best-practices-part-2/

Thanks in advance.

**Comment by nvquanghuy** [comment]
Hi @nfaugout-lucca , thank you I'm glad you like it! Can you repost this into dbdiagram community forum pls? The github is for DBML, the syntax. The 2 are related but separate projects.

https://community.dbdiagram.io/

Cheers.
