### ISSUE TITLE
Need support comment on mysql and another

### ISSUE THREAD

**Issue by tritueviet** [holistics/dbml#450]
ex: create table schema_migrations
(
    version bigint     not null
        primary key,
    dirty   tinyint(1) not null comment "dirty 1 for dirty other is not dirty"
);

need convert sql2sbml working find

**Comment by nguyenalter** [comment]
Hi @tritueviet,

We do support column comments in MySQL (implemented in https://github.com/holistics/dbml/pull/252)

Our parser currently does not recognize the `comment` word. We will fix this issue soon.

As a workaround, you can change the word `comment` to `COMMENT`.

**Comment by tritueviet** [comment]
thanks u for support. It worked
