### ISSUE TITLE
Postgres export fails on array

### ISSUE THREAD

**Issue by mkaatman** [holistics/dbml#46]
I posted here: https://community.dbdiagram.io/t/postgres-array-export-fails/416

I'm not sure if the export of dbdiagram.io is considered part of dmbl or not but I thought I'd create an issue for it.

Postgres expects the following syntax for array types:

```
CREATE TABLE contacts (
    variants TEXT []
);
```
When I use:

`variants array`
It exports as:

`"variants" array,
`
which fails.

User error on my part?

**Comment by phuongduyphan** [comment]
Hi @mkaatman ,

Actually array type hasn't supported for exporting yet. As I see, this array data type concept only supported by PostgreSQL so at this time we decide not to implement this in DBML. However, we do have a plan to introduce a new syntax called dialect annotation to solve the concept mismatch problem across databases. 

Will keep you informed when the new syntax is out.

**Comment by mkaatman** [comment]
Thanks for clarification. Are there docs on the supported data types? I only saw one note here:

https://www.dbml.org/docs/

> type of the data in the column listed as column_type
> supports all data types, as long as it is a single word (remove all spaces in the data type). Example, JSON, JSONB, decimal(1,2), etc.

**Comment by phuongduyphan** [comment]
Sorry it's my bad, I've just looked into the docs and the parser implementation again, it turned out we do support all the data types, including arrays. The array syntax is like this: `text[]` without spaces between the type name and the brackets. But somehow the parser recognized the brackets as the field options. This is the bug on our side. We will fixed this asap.

Will keep you updated when the patch is released. Thank you!

**Comment by mkaatman** [comment]
Thanks for the update. Is the parser on github also? I'd be interested in following that project as well.

**Comment by phuongduyphan** [comment]
Yes, you can check it out here: https://github.com/holistics/dbml/tree/master/packages/dbml-core

**Comment by robinator** [comment]
I'm hitting this same kind of error running `dbdocs build` 

```
# offending line
"onboarding_alt_pii_fields" "varchar[]" [not null, default: 'ARRAY[_name, date_of_birth}']']
```
```
Syntax error at line 1049 column 93. Invalid newline encountered while parsing
Syntax error at line 1049 column 43. Expect a following space
Syntax error at line 1049 column 43. These fields must be some inline settings optionally ended with a setting list
Syntax error at line 1051 column 3. These fields must be some inline settings optionally ended with a setting list
Syntax error at line 1051 column 11. These fields must be some inline settings optionally ended with a setting list
```

Is there a better place to report this?
