### ISSUE TITLE
MySQL sql2dbml fails on comments

### ISSUE THREAD

**Issue by darkwitch** [holistics/dbml#461]
I tried sql2dbml on my project and was suprised that comments (field and table level) are not supported:

```create table TEST
(
    ID varchar(100) not null comment 'id of table'
);

Fails with:
`ERROR: You have a syntax error at "comment_test.sql" line 3 column 5. Expected ")" or fields but "I" found.`

**Comment by nguyenalter** [comment]
We do support table and field comments in MySQL (implemented in #252)

The issue you mentioned is caused by our parser does not recognize the "comment" word. We have fixed it in #460
