### ISSUE TITLE
Proposal: Schema Concept for DBML

### ISSUE THREAD

**Issue by phuongduyphan** [holistics/dbml#50]
# Schema

## Overall structure of DBML
![DBML AST Normalized Format](https://user-images.githubusercontent.com/32348670/72796402-d7efa800-3c71-11ea-90ab-4faf8c43bd53.png)

## Schema syntax
```
Schema ecommerce {
  Table users {
    id int [pk]
    name varchar
  }

  Note: 'ecommerce schema'
}

// or

Table ecommerce.users {
  id int [pk]
  name varchar
}
```
Two syntaxes to define schema:
* Define schema explicitly `Schema <schema-name> { ... }`
* Implicitly define schema through table name `Table <schema-name>.<table-name>`

From the time the schema concept is introduced, tables, enums, table groups and refs that don't have prefix schema name will belong to the default `public` schema. Exporting DBML to SQL will not export the default `public` schema syntax if in the DBML code the `public` schema is not explicitly defined.

```
Table users {    // public schema syntax will not export to SQL
  id int [pk]
  name varchar
}

// is the same as

Table public.users {  // public schema syntax will export to SQL.
  id int [pk]
  name varchar
}
``` 

Schema contains:
* tables
* enums
* table groups
* refs

References between tables in different schemas are possible:

```
Table ecommerce.users {
  id int [pk]
  tracking_id int [ref: > snowplow.users.id]  // reference to id of user in schema snowplow
  name varchar
  email varchar
}

Table snowplow.users {
  id int [pk]
  ip varchar
  location varchar
}
```

**Comment by aisbergde** [comment]
Is there any progress on the implementation of Schemas? Are there plans to implement this?

**Comment by NQPhuc** [comment]
Implemented in https://github.com/holistics/dbml/pull/240
