### ISSUE TITLE
@dbml/cli bug: postgres foreign keys generated in reverse

### ISSUE THREAD

**Issue by galaczi** [holistics/dbml#502]
For Postgres the cli tries to create foreign keys in reverse. E.g. for this structure:

```
Table users {
  id integer [pk]
  username varchar
}

Table user_profiles {
  id integer [pk]
  user_id integer [ref: - users.id] // one-to-one relationship
  bio text
  avatar_url varchar
}
```

It generates:

```ALTER TABLE "users" ADD FOREIGN KEY ("id") REFERENCES "user_profiles" ("user_id");```

It should alter ``user_profiles``. The app on dbdiagram works correctly so that's what I am using in the meantime.

**Comment by NQPhuc** [comment]
Hi @galaczi,

Thanks for report,

There appear to a a reverse in reference's fields ordering for inline relationship in the new DBML version 3. We'll take a long and fix it sometime in the future.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/507
