### ISSUE TITLE
Proposal: Multi-line String for DBML

### ISSUE THREAD

**Issue by phuongduyphan** [holistics/dbml#51]
## Objective
* Support writing long string that can span over multiple lines
* Support writing markdown for DBML Note

## Syntax
Multiline string will be defined between triple single quote '''

```
Note: '''
  # DBML - Database Markup Language

  [![Build Status](https://travis-ci.org/holistics/dbml.svg?branch=master)](https://travis-ci.org/holistics/dbml)
	
	
  DBML (database markup language) is a simple, readable DSL language designed to define database structures.
  For more information, please check out [DBML homepage](https://dbml.org)
'''
```

* Line breaks: \<enter\>
* Line continuation `\`:

```
Note: '''
  This is a very long long \
note.
'''

=> Result: 

This is a very long long note.
```

* Escape triple single quote in multi-line string \\'''
```
Note: '''
  Sample note in DBML
	
  Note: \'''
    Note in DBML
  \'''
'''

=> Result:

Sample note in DBML

Note: '''
  Note in DBML
'''
```

* The number of spaces you use to indent a block string will be the minimum number of leading spaces among all lines. The parser will automatically remove the number of indentation spaces in the final output.

Example:
````
Note: '
  if (a === b) {   // 2 spaces indentation
    c = a + b;     // 4 spaces
  }                // 2 spaces
'

=> result: automatically remove 2 leading whitespaces at the beginning of each line

if (a ===b) {
  c = a + b;
}
````

**Comment by nvquanghuy** [comment]
Is there a difference between the use of single quote and double quote? Is double quote allowed?

**Comment by NQPhuc** [comment]
Implemented in https://github.com/holistics/dbml/pull/47
