### ISSUE TITLE
Using guids

### ISSUE THREAD

**Issue by PhilipAnd** [holistics/dbml#58]
Hi,

Is it possible to use Guids as ID's - I can't seem to find anything related to this in the documentation?

**Comment by phuongduyphan** [comment]
Can you elaborate more on your use cases?

Here is an example of exporting guid type from DBML to PostgreSQL

DBML:
```
Table users as U {
  id uuid [default: `uuid_generate_v4()`]
  full_name varchar
  created_at timestamp
  country_code int
}
```

Export to PostgreSQL:
```
CREATE TABLE "users" (
  "id" uuid DEFAULT (uuid_generate_v4()),
  "full_name" varchar,
  "created_at" timestamp,
  "country_code" int
);
```

**Comment by PhilipAnd** [comment]
I must have missed it in the documentation. This is exactly what I was looking for. Thanks!
