### ISSUE TITLE
index shortcut for single-column indexes

### ISSUE THREAD

**Issue by datashaman** [holistics/dbml#6]
Just like you have `unique` setting for a column, an `index` setting would be convenient for single-column indexes. Here's an example for a table generated with a fresh Laravel installation:
```
Table password_resets {
    email varchar [index]
    token varchar [not null]
    created_at timestamp
}
```

**Comment by JiawenKor** [comment]
Hi @datashaman, we will be releasing our index syntax soon and it will look like this:
```
Indexes {
	created_at [name: "Date"],
	(country, booking_date),
	(country) [unique]
	booking_date [type: gin]
	`lower(name)`
}
```
This will allow more details to be added together with `index`. Will this be helpful for you? 
Also, do stay tuned to our releases on our Release Notes here! https://dbdiagram.noting.io/
Thank you.

**Comment by datashaman** [comment]
I've written a _peg.js_ grammar for _DBML_. I'd be interested to compare it to yours if you have one and you're willing to share.

**Comment by datashaman** [comment]
I'd also like to know what you think of me sharing the grammar. There is no licence on the format repository.

**Comment by JiawenKor** [comment]
Hi @datashaman, we have plans to open source our parser soon. Stay tuned!

**Comment by nntai** [comment]
hi @datashaman , we did open-source our parser, which was written peg.js. You could check in [dbml-core](https://github.com/holistics/dbml/tree/master/packages/dbml-core)
