### ISSUE TITLE
Generate DBML from SQLServer Fail

### ISSUE THREAD

**Issue by MisterGeek** [holistics/dbml#630]
When I try to generate my DBML from my databsae, I've got an error : 
"Error: Error: Field "CA_VERSION" existed in table  "dbo"."C_VERSION"

I don't understand why. 
This is the strucure of my table : 

```tsql
CREATE TABLE [dbo].[C_VERSION](
  [CA_IDENT] [numeric](28, 0) NOT NULL,
  [CA_VERSION] [numeric](4, 2) NOT NULL,
  [CA_VERSION_COMMENT] [nvarchar](4000) NULL,
  [CA_VERSION_DATE] [datetime] NULL,
  [CA_VERSION_UTI] [numeric](28, 0) NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[C_VERSION] ADD  CONSTRAINT [PK_CA_IDENT] PRIMARY KEY CLUSTERED 
(
  [CA_IDENT] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]

CREATE NONCLUSTERED INDEX [idx_pfk_23] ON [dbo].[C_VERSION]
(
  [CA_VERSION_UTI] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, FILLFACTOR = 100) ON [PRIMARY]

ALTER TABLE [dbo].[C_VERSION]  WITH CHECK ADD  CONSTRAINT [NN_CA_VERSION_DATE] CHECK  (([CA_VERSION_DATE] IS NOT NULL))
ALTER TABLE [dbo].[C_VERSION] CHECK CONSTRAINT [NN_CA_VERSION_DATE]
ALTER TABLE [dbo].[C_VERSION]  WITH CHECK ADD  CONSTRAINT [NN_CA_VERSION_UTI] CHECK  (([CA_VERSION_UTI] IS NOT NULL))
ALTER TABLE [dbo].[C_VERSION] CHECK CONSTRAINT [NN_CA_VERSION_UTI]
GO
```

**Comment by huyleminh01** [comment]
Hi @MisterGeek ,

We tried to reproduce your case using our connector and confirm that this is a bug. We will investigate and fix this soon.

Also, could you provide us with your:

- Current database version.
- Current running environment: docker (image version) or Microsoft SQL Server, etc.

Thanks.

**Comment by MisterGeek** [comment]
Current database version : SQL Server 2019
Current running environment: docker (image version) or Microsoft SQL Server, etc. : Microsoft SQL Server

I try on SQL Server 2017 and i've got the same error. 
Thanks in advance and great job, as I've been waiting for this feature for a long time and it will allow me to abandon my SQL queries to generate my dbml :-)

**Comment by huyleminh01** [comment]
Hi @MisterGeek ,

Thank you for your quick reply and your compliment!

We'll keep working to resolve this problem.

**Comment by huyphung1602** [comment]
Hi @MisterGeek,

We released a new dbml version to fix your issue. Please re-run `npm install -g @dbml/cli` to install the latest dbml version and help us to re-try the command on your end.

**Comment by MisterGeek** [comment]
Hi @huyphung1602 ,
It's work like a charm. 
I generate my dmbl file in a few seconds for my database with over 800 tables and 16 000 fields ! 

Perfect ! 👍  thanks a lot.
