### ISSUE TITLE
The dbml v2 parser has included the enum arguments in the type_name

### ISSUE THREAD

**Issue by allanclempe** [holistics/dbml#641]
## Problem:

The dbmlv2 parser includes enum arguments in the type_name property, which did not happen in the previous version of the parser.

## Example 

Using the following dbml: 

```ts
const dbml = `Table lead_status_history {
  status enum(contacted, converted, not_contacted)
}`
```

Then run the parser:

```ts
const p = new Parser();
const database = p.parse(dbml, 'dbmlv2');

const allTypes = database.schemas.flatMap((item) =>
        item.tables.flatMap(
          (item) => item.fields.flatMap((item) => item.type) 
        )
      );

console.info(allTypes)
```
returns:

```ts
[{
        type_name: 'enum(contacted,converted,not_contacted)',
        args: 'contacted,converted,not_contacted'
}]
```
expected result:

```ts
[{
        type_name: 'enum',
        args: 'contacted,converted,not_contacted'
}]
```

**Comment by Huy-DNA** [comment]
Hi @allanclempe, thanks for your feedback.
It's indeed correct that this has changed in dbml parser v2.
However, the DBML syntax document never specifies this DBML "inline enum" syntax:
```
Table User {
   status  enum(contacted,converted,not_converted)
}
```
Can you explain some context of your use case?

**Comment by allanclempe** [comment]
That make sense, not sure where I got that syntax from, but just went through the documentation and makes more sense to have a specific definition for it.

Closing this one for now, thanks.
