### ISSUE TITLE
Missing: npm install dbdocs returns 404

### ISSUE THREAD

**Issue by MicahRCM** [holistics/dbml#66]
Either needs a documentation update or a republishing/register of the cli package.

Docs describing npm install: https://dbdocs.io/?utm_source=dbdiagram&utm_medium=top_menu&utm_campaign=launch_dbdocs

```
npm install dbdocs
```

```
npm ERR! code E404
```

**Comment by phuongduyphan** [comment]
Hi @MicahRCM ,

Actually we haven't released dbdocs yet. If you're already signed up for early access, you will be received an invitation email to participate in an early adopter version of the product as soon as it's ready.
