### ISSUE TITLE
MySQL backticks causing syntax error in CLI

### ISSUE THREAD

**Issue by schmod** [holistics/dbml#67]
When I quote identifiers with backticks (a fairly typical MySQL convention), I'm unable to use the CLI to import a schema:

```
CREATE TABLE `users` (
  `user_id` int(11),
  PRIMARY KEY (`user_id`)
);
```

```
$ sql2dbml ~/Documents/db/users.sql
   ERROR: You have a syntax error at "users.sql" line 1 column 14. Expected "IF" or valid table name but "`" found.
```

**Comment by phuongduyphan** [comment]
Hi @schmod ,

I believe you forgot to specify database option in your command. Here is the correct one:
```
$ sql2dbml --mysql schema.sql
```

Please refer to the docs for more details: https://www.dbml.org/cli/#syntax-manual
