### ISSUE TITLE
support for timestamptz

### ISSUE THREAD

**Issue by jeffbum** [holistics/dbml#71]
when converting from postgres --> dbml, timestamptz is not supported. Can switch in sql documentation to timestamp, just complicates it further than needed to be. Output of timestamp in dbml is fine as well.

**Comment by jeffbum** [comment]
found, if I change timestamptz to 'timestamp with time zone', it generates just as well. It's a little work on my end, but should not be too difficult. would still like to see timestamptz conversion just the same.

**Comment by nvquanghuy** [comment]
Hi @jeffbum, sorry I missed this. I don't quite understand why timestampz is not supported when converting from postgres -> dbml. Can you share reproduction steps pls?

**Comment by incompletude** [comment]
```sql
CREATE TABLE "public"."payment" (
    "id_payment" int8 NOT NULL DEFAULT nextval('payment_id_payment_seq'::regclass),
    "created_at" timestamptz NOT NULL,
    PRIMARY KEY ("id_payment")
);
```

It is quite simple, this will break the cli while it is completely fine PostgreSQL script.

**Comment by csangonzo** [comment]
+1

**Comment by khoahuynhdev** [comment]
+1
