### ISSUE TITLE
No history or undo = frustration

### ISSUE THREAD

**Issue by Chukatuk** [holistics/dbml#77]
So i've just wasted a couple of hours on building a diagram, first time using the tool...
Wrote some lines of code, gave it a name and saved.

Finished writing down tables, wanted to see some examples so i clicked "Load Sample" and thought it will open a new window... 
But guess what? It overwrites your code! (But who knows?)

And than i could find mine, started opening new tabs, panicked a bit and not sure wtf did i do..
As a result, my code is gone and no way to get it back...
Bye bye 2 hours! 
This is really frustrating...

**Comment by phuongduyphan** [comment]
I'm sorry for the frustration and confusion the "Load Sample" has caused. This will be fixed asap. FYI, history of saved edits, aka version control for diagrams will be available towards end of Q2 2020. Will keep you updated on the progress.

Ps: If you encounter any further issues from dbdiagram, please post it here in our community forum instead: https://community.dbdiagram.io/.
