### ISSUE TITLE
Postgres "time with zone" type does not parse

### ISSUE THREAD

**Issue by GavinRay97** [holistics/dbml#78]
Trying to parse the below throws an error on `time with zone`:
```sql
CREATE TABLE public.hours_of_operation (
  id integer NOT NULL,
  created_at timestamp with time zone DEFAULT now() NOT NULL,
  updated_at timestamp with time zone DEFAULT now() NOT NULL,
  location_id integer NOT NULL,
  day text NOT NULL,
  open time with zone NOT NULL,
  close time with zone NOT NULL
);
```

**Comment by phuongduyphan** [comment]
Currently, "time with zone" is not supported in our postgres parser yet.

It's already in our roadmap. Will keep you informed when it's added.

**Comment by phuongduyphan** [comment]
Currently, `time with zone` hasn't been supported in our postgres parser yet. 

This will be added to our roadmap. Will keep you informed when it's implemented.

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/150
