### ISSUE TITLE
allow NOW() default value for timestamp without the single quotation

### ISSUE THREAD

**Issue by kenng** [holistics/dbml#8]
Thanks for the nice tool!~

There's a small issue when importing the timestamp type into the database when using  
    
     created_at timestamp [default: `now()`]
     updated_at timestamp [default: 'now()']

This will be exported as  

    created_at timestamp DEFAULT (now()),
    updated_at` timestamp DEFAULT 'now()'

Both of the outputs cause error during the import. 

Supported syntax are
    
    `created_at` timestamp DEFAULT now(),
    `updated_at` timestamp DEFAULT CURRENT_TIMESTAMP

**Comment by cottonball97** [comment]
Hi, i'm from Dbdiagram Team,
With now() you should wrap it between the backtick as `now()` since 'now()' will be exported as a string, not a function. 
I'm testing the code `created_at timestamp DEFAULT (now())` in MySQL 8.0.16 and it's working fine :D 
About the import feature, the new version will be deployed within this week so stay tuned and this problem will be resolved ^^ 
Thanks for your feedback!

**Comment by kenng** [comment]
That would be awesome! Let us know when it's updated

**Comment by cottonball97** [comment]
The new parser for import has been released! You can now import `DEFAULT CURRENT_TIMESTAMP` & `DEFAULT now() `smoothly :) 
We did our best but it still seems to be buggy so please do give it another round and tell us if there's anything wrong happened to you. We're happy to help!

**Comment by kenng** [comment]
Ops, I am sorry as I think I have misled you. The original issue is with exporting to MYSQL from the dbdiagram. 

I have just tested again to export syntax
```created_at timestamp [default: `now()`]```

the MYSQL syntax being exported is 
```
`created_at` timestamp DEFAULT (now())
```
This will make MYSQL 5.7.18 to throw error
```
You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '(now())
)'
```

Supported syntax is (without additional parenthesis wrapping the now())
```
`created_at` timestamp DEFAULT now()
```

**Comment by blessedjasonmwanza** [comment]
Hi @cottonball97 , I have been reading up online and can't seem to find documentation on how to implement ON UPDATE CURRENT_TIMESTAMP using DbDiagram. 

May you kindly share some Intel on how I can implement the ON update function?
your help will be highly appreciated/>

**Comment by Arslan90** [comment]
Hello, thanks for this handful tool, but I would like to point out that the issue is still unsolved for MySQL5.7 version

**Comment by xuliang520914** [comment]
```
created_at "timestamp default CURRENT_TIMESTAMP" [not null,note:'create time']
updated_at "timestamp default CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP" [not null,note:'update time']
```

**Comment by XedinUnknown** [comment]
Yep, this is certainly still manifests on MySQL 5.6, which is still the most used version around. Please correct this: the docs claim that it will convert between DBML and MySQL no problem, but it certainly is not, at least in dbdiagram.io. I'm not sure if it is supposed to correspond 1:1 with latest DBML, but I'm not sure why it wouldn't be.
