### ISSUE TITLE
Better identification of required(not null) fields

### ISSUE THREAD

**Issue by woprrr** [holistics/dbml#84]
Actually when we define a field as required we can't seen directly in rendered diagrams theses fields.

`  details varchar(255) [not null]` by example will display a small * after field name or another hightlight information will be more clear and useful.

Thank you for that great app !!!

**Comment by nvquanghuy** [comment]
Thank you for sharing! As this is related to dbdiagram instead of DBML, I'll move this over to dbdiagram community forum at: https://community.dbdiagram.io/
