### ISSUE TITLE
Python parser for DBML

### ISSUE THREAD

**Issue by Vanderhoof** [holistics/dbml#88]
Hey, guys!
I couldn't find any contacts but found this quote on DBML.org: 

> Have a question, suggestion or want to contribute? Use the dbml issues page 

So I'm writing here.

We love your DBML syntax, it's simple (unlike SQL), easy to learn for our analysts and is just perfect for database architecture stage.

But we needed a way to embed the DBML schemas into our static site, and since we use Python-tools for our documentation workflows, I've made a [Python parser](https://github.com/Vanderhoof/PyDBML/) for DBML syntax, I thought it may be useful for pythonists out there. I'd be glad if you checked it out.

We use [Foliant](https://github.com/foliant-docs/foliant) + [MkDocs](https://github.com/mkdocs/mkdocs) for our static sites, so I've also built a Foliant [preprocessor](https://foliant-docs.github.io/docs/preprocessors/dbmldoc/), which uses the parser to parse DBML scheme and passes it through template to create a Markdown page, which results in the following simple and clean database documentation page:

<img width="1169" alt="doc" src="https://user-images.githubusercontent.com/12543857/80459946-cc301380-893b-11ea-83a4-645ffe2f4ad5.png">

Hope this helps somebody. Thank you again for the great job!

**Comment by nvquanghuy** [comment]
Hi @Vanderhoof, really glad you like DBML! To respond to your comment above:

1- There are 2 ways to generate static/embed sites for DBML. First, you can consider using the Embed feature of dbdigram.io, it gives you an iframe that you can embed to your site. Second, you can check out our most recent project: dbdocs.io

Does any of these 2 work for you?

2- Glad that you have created a Python parser/docs for DBML. If you want to have it included in our project, feel free to open a PR to add to our `README.md` file!

**Comment by Vanderhoof** [comment]
@nvquanghuy thank you for your kind reply!
1. The first way, with dbdiagram.io won't work for us, because we use "docs as code" approach and all documenting tools should be a part of a pipeline. But dbdocs project looks very interesting! I've applied to the beta and hope to look into it tomorrow

2. Thanks for this suggestion, I will be honored!

**Comment by nvquanghuy** [comment]
That's awesome to hear @Vanderhoof. And I love that you mention "docs as code", because dbdocs is designed to follow "database as code" philosophy.

And we provide CLI on purpose, so that you can make it part of your deployment workflow too.
