### ISSUE TITLE
Decimal data type

### ISSUE THREAD

**Issue by ledsonsilva** [holistics/dbml#9]
Hello, I'm really enjoying the tool, and in my modeling I'm doing, I ended up noting that when using the decimal data type, if I need to put a decimal range (10,2) that I usually use for money values does not work, is giving error and leaves the modeling with bugs ... It would be interesting that it worked so much for decimal, float etc ...

**Error:**
![image](https://user-images.githubusercontent.com/20303042/61176257-20782b80-a594-11e9-96f4-c77ecd49cc36.png)

**No error:**
![image](https://user-images.githubusercontent.com/20303042/61176266-35ed5580-a594-11e9-9efe-ff8b2645813e.png)

**Comment by JiawenKor** [comment]
Hi @ledsonsilva, I'm from the dbdiagram.io team. Thank you for sharing about the decimals and float data types! I have added your feedback into our roadmap and we will keep you updated about the progress.

**Comment by nvquanghuy** [comment]
Hi @ledsonsilva , this can be fixed by removing the space in the data type:

```Table deals {
  id integer [pk]
  price decimal(1,2)
}```

**Comment by ledsonsilva** [comment]
> Hi @ledsonsilva , this can be fixed by removing the space in the data type:
> 
> ```
> Table deals {
>   id integer [pk]
>   price decimal(1,2)
> }
> ```

It worked! Thank you :smile:
