### ISSUE TITLE
sql2dbml cannot parse MySQL field level character set/charset

### ISSUE THREAD

**Issue by Orclyx** [holistics/dbml#94]
With the following SQL:

```sql
CREATE TABLE `example` (
  `id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL
) ENGINE=InnoDB COLLATE=utf8mb4_unicode_ci;
```

`sql2dbml --mysql` will return:
> ERROR: You have a syntax error at "untitled.sql" line 2 column 3. Expected ")" or fields but "`" found.

Removing `CHARACTER SET utf8mb4` results in expected behaviour:
> Table "example" {
>  "id" varchar(255) [default: NULL]
> }

**Comment by NQPhuc** [comment]
Fixed in https://github.com/holistics/dbml/pull/95
