### ISSUE TITLE
Png export does not work in Firefox for Linux

### ISSUE THREAD

**Issue by Makistos** [holistics/dbml#97]
All I get is "Something went wrong." in Firefox in a popup window top right and reload error in Chrome. I did manage to export in Chrome at first but not anymore.

**Comment by nvquanghuy** [comment]
Thanks for reporting this Makistos. This issue is related to dbdiagram so I have transferred your post over to the forum here: 

https://community.dbdiagram.io/t/bugs-png-export-does-not-work-in-firefox-for-linux/619
